#:schema node_modules/wrangler/config-schema.json
name = "transfer-worker"
main = "src/worker.jsx"
compatibility_date = "2024-07-24"
compatibility_flags = ["nodejs_compat"]

kv_namespaces = [
  { binding = "SUBLINK_KV", id = "754fc0f747d448f7a553535ddcc75558" }
]

[assets]
directory = "./public"
